services:
  - type: web
    name: cleaningup
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: MONGO_URI
        value: <TU_URI_DE_MONGODB>
